### ISSUE TITLE
Actualizar sección de "Tecnologías elegidas" en la wiki

### ISSUE THREAD

**Issue by robgc** [EGC-G2-Trabajo-1718/autenticacion#2]
El proyecto deberá funcionar utilizando una base de datos MySQL a la que se conectará el subsistema desarrollado. No es posible usar SQLite.
No parece que Django de por sí permita crear una API Rest de base, pero hay otras herramientas que si lo permiten (Django Rest Framework).
Todas las dependencias se pueden incluir en un archivo llamado "requirements.txt" con su versión correspondiente en Python. Este archivo podría incluirse en el repositorio.

**Comment by espisepi** [comment]
Actualizada la wiki.
