### ISSUE TITLE
Popular el proyecto con MySQL con los datos de la API correspondiente

### ISSUE THREAD

**Issue by espisepi** [EGC-G2-Trabajo-1718/autenticacion#23]
**Prioridad:** Alto
**Estado:** En curso
**Descripción:** Añadir los datos que se tenían en el proyecto con sqlite3 al proyecto con mysql, para ello añade a tu rama el nuevo proyecto con mysql, tienes dos opciones para trabajar:

1. Si no quieres trabajar con Docker:

- En el archivo requirements.txt está todo lo que hay que descargar con pip install para que funcione el proyecto.

- tendrías que instalar mysql a parte buscando un tutorial por internet.

2. Si quieres trabajar con Docker:

- Lo primero es en el terminal ir a la carpeta donde están todos los archivos de manage.py,docker-compose.yml,dockerfile... y una vez dentro escribir:
$ sudo docker-compose build

- Lo siguiente, para utilizar manage.py hay que escribir el siguiente comando:
$ sudo docker-compose run --rm djangorest python manage.py loquesequieraponer

Ejemplo para migrar la base de datos: $ sudo docker-compose run --rm djangorest python manage.py migrate

**Solucionado por Tania**
**IMPORTANTE**: Para migrar la base de datos utilizar el comando $ sudo docker-compose run --rm djangorest python  manage.py makemigrations principal
**No utilizar**:  $ sudo docker-compose run --rm djangorest python manage.py migrate

- Para levantar el servidor desde docker, escribir el siguiente comando:
$ sudo docker-compose up

**Si docker-compose te da problemas, instala docker-compose como se indica por internet y además instalalo mediante pip install docker-compose**

**Comment by tanitasa** [comment]
Para popularla se ha de crear un superusuario con el siguiente comando en docker: sudo docker-compose run --rm djangorest python manage.py createsuperuser . Posteriormente, se ejecutaran los siguientes comandos por orden, para hacer las migraciones y levantar el servidor: sudo docker-compose run --rm djangorest python manage.py makemigrations principal ; sudo docker-compose run --rm djangorest python manage.py migrate ; sudo docker-compose up. Luego entramos a 0.0.0.0:8000/admin, nos logueamos con el superusuario creado y añadimos los usuarios.
