### ISSUE TITLE
Funcionalidad de "obtener los usuarios de un rol/grupo" a partir del nombre del rol/grupo.

### ISSUE THREAD

**Issue by migueltern** [EGC-G2-Trabajo-1718/autenticacion#7]
Prioridad: alta
Estado:  pendiente
Descripción: 
Desde administración de censos necesitamos obtener un ROL/GRUPO para agrupar a los Usuarios de ese ROL/GRUPO en un censo.

Opción 1: Convertir atributo "role" de User en tabla "grupo" y añadir funcionalidad de "/getRole" o "/getGroup":
Opción un poco compleja ya que requiere de cambiar vuestro modelo. Consiste en que el atributo "role" de un User sea un objeto/tabla relacionado con User, o en su defecto que creen el objeto/tabla/clase Group(id, name) para que almacene los valores que vosotros habéis definido como "role" (ASISTENTE, PONENTE, AMBOS, ETC).
¿Por qué?: Inicialmente nos simplificaría (tanto a nosotros como a los servidores) la obtención de todos los User que pertenezcan a ese Group (léase "role") para otorgar con ello a todos los miembros acceso a una votación determinada (mediante un censo).

Opción 2: Agregar un id_usuario o hacer "username" único y añadir funcionalidad de "/getUsersByRole" a partir de un "role":
La opción más sencilla y preferible. Esto nos ayudaría a no tener conflictos al buscar usuarios por id / nombre único (ya que actualmente podrían existir conflictos al no especificarse que sea único), y mediante "/getUsersByRole" obtener esa lista de usuarios (que podremos identificar por nombre/id_usuario sin problemas) que pertenecen a un censo.
Si se elige esta opción nosotros simplemente tendríamos que cambiar algunos parámetros en nuestra API y especificarlos.

Nota: las nomenclaturas usadas no tienen por qué seguirse al pie de la letra, solo fueron sugerencias para mejorar la explicación.

**Comment by tanitasa** [comment]
Lo hemos resuelto de la segunda forma que nos proponéis. Ahora "username" es único y hemos añadido el método /getUsersByRole/<role>, el cual nos devuelve todos los usuarios que pertenecen al role que le pasamos.
